# destination 'todos' is the rendezvous between the output and input channel
spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: todos-sink
